// elmapicms-templates/nextjs-sable-goods/components/site-header.tsx
import Link from "next/link";
import { AuthNav } from "@/components/auth-nav";
import { MobileNav } from "@/components/mobile-nav";
import { ShopMegaMenu } from "@/components/shop-mega-menu";
import type { CategoryTreeNode } from "@/lib/categories";
import type { ContentEntry, SiteSettingsFields } from "@/lib/types";

const OTHER_LINKS = [
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
  { label: "Shipping", href: "/shipping" },
  { label: "FAQ", href: "/faq" },
];

export function SiteHeader({
  settings,
  categoryTree,
  cartCount = 0,
}: {
  settings: ContentEntry<SiteSettingsFields>;
  categoryTree: CategoryTreeNode[];
  cartCount?: number;
}) {
  const siteName = settings.fields["site-name"] || "Sable Goods";

  return (
    <header className="relative sticky top-0 z-50 border-b border-border bg-white">
      <div className="mx-auto grid max-w-7xl grid-cols-[1fr_auto_1fr] items-center gap-4 px-5 py-5 sm:px-8">
        <div className="flex items-center gap-3 justify-self-start">
          <div className="lg:hidden">
            <MobileNav categoryTree={categoryTree} />
          </div>
          <nav className="hidden items-center gap-6 lg:flex">
            <ShopMegaMenu tree={categoryTree} />
            {OTHER_LINKS.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className="text-[11px] font-semibold uppercase tracking-[0.16em] text-ink/70 transition-colors hover:text-ink"
              >
                {item.label}
              </Link>
            ))}
          </nav>
        </div>

        <Link href="/" className="justify-self-center text-center">
          <span className="brand-mark">{siteName}</span>
        </Link>

        <div className="justify-self-end">
          <AuthNav cartCount={cartCount} />
        </div>
      </div>
    </header>
  );
}

// elmapicms-templates/nuxt-cove/app/components/SiteHeader.vue
<script setup lang="ts">
const props = defineProps<{
  siteName?: string
  primaryLabel?: string
  primaryUrl?: string
}>()

const items = [
  { label: 'Features', to: '/features' },
  { label: 'Pricing', to: '/pricing' },
  { label: 'Changelog', to: '/changelog' },
  { label: 'Blog', to: '/blog' },
  { label: 'About', to: '/about' },
  { label: 'Contact', to: '/contact' }
]

const open = ref(false)
</script>

<template>
  <header class="sticky top-0 z-50 border-b border-black/5 bg-white/90 backdrop-blur-md">
    <div class="cove-wrap flex h-16 items-center justify-between gap-4">
      <NuxtLink to="/" class="shrink-0" @click="open = false">
        <CoveLogo :name="props.siteName || 'Cove'" />
      </NuxtLink>

      <nav class="hidden items-center gap-7 lg:flex" aria-label="Primary">
        <NuxtLink
          v-for="item in items"
          :key="item.to"
          :to="item.to"
          class="text-sm font-medium text-ink-600 transition hover:text-ink-900"
        >
          {{ item.label }}
        </NuxtLink>
      </nav>

      <div class="flex items-center gap-3">
        <UButton
          class="hidden sm:inline-flex"
          :to="props.primaryUrl || '/pricing'"
          color="primary"
          size="md"
        >
          <span class="text-forest-900">{{ props.primaryLabel || 'Start free' }}</span>
        </UButton>
        <button
          type="button"
          class="flex h-10 w-10 items-center justify-center lg:hidden"
          :aria-label="open ? 'Close menu' : 'Open menu'"
          @click="open = !open"
        >
          <span class="flex w-5 flex-col gap-1.5">
            <span class="h-0.5 w-full bg-ink-900" />
            <span class="h-0.5 w-full bg-ink-900" />
          </span>
        </button>
      </div>
    </div>

    <div
      v-if="open"
      class="border-t border-black/5 bg-white lg:hidden"
    >
      <nav class="cove-wrap flex flex-col gap-1 py-4" aria-label="Mobile">
        <NuxtLink
          v-for="item in items"
          :key="item.to"
          :to="item.to"
          class="rounded-xl px-3 py-2.5 text-base font-medium text-ink-700 hover:bg-ink-50"
          @click="open = false"
        >
          {{ item.label }}
        </NuxtLink>
        <UButton
          class="mt-2"
          :to="props.primaryUrl || '/pricing'"
          color="primary"
          block
          @click="open = false"
        >
          <span class="text-forest-900">{{ props.primaryLabel || 'Start free' }}</span>
        </UButton>
      </nav>
    </div>
  </header>
</template>
