// elmapicms-templates/nextjs-ridgeform/app/about/page.tsx
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { PageIntro } from "@/components/page-intro";
import { Reveal } from "@/components/reveal";
import { RichText } from "@/components/rich-text";
import { assetAlt, firstAsset } from "@/lib/assets";
import {
  getAboutPage,
  getServices,
  getSiteSettings,
  getTeamMembers,
} from "@/lib/content";
import { buildMetadata } from "@/lib/seo";

export async function generateMetadata(): Promise<Metadata> {
  const [settings, page] = await Promise.all([getSiteSettings(), getAboutPage()]);
  const image = firstAsset(page.fields.image);
  return buildMetadata({
    settings,
    title: page.fields["meta-title"] || "About",
    description: page.fields["meta-description"] || page.fields.intro,
    path: "/about",
    imageUrl: image?.url,
  });
}

export default async function AboutPage() {
  const [page, team, services, settings] = await Promise.all([
    getAboutPage(),
    getTeamMembers(),
    getServices(),
    getSiteSettings(),
  ]);
  const image = firstAsset(page.fields.image);
  const featuredServices = services.filter((service) => service.fields.featured);
  const specialization =
    featuredServices.length > 0 ? featuredServices.slice(0, 4) : services.slice(0, 4);

  return (
    <>
      <PageIntro
        title={
          page.fields.title ||
          "Creating quality urban lifestyles, building stronger communities."
        }
        breadcrumbs={[
          { label: "Home", href: "/" },
          { label: "About" },
        ]}
      />

      <section className="dot-bg py-20">
        <div className="site-shell grid items-center gap-12 md:grid-cols-2">
          <Reveal>
            <span className="section-label">About Company</span>
            <p className="mt-4 text-sm font-bold uppercase tracking-wider text-safety">
              {settings.fields["years-label"] || "18 Years of Experience"}
            </p>
            <h2 className="font-heading mt-3 text-3xl font-extrabold uppercase leading-tight md:text-4xl">
              Improving quality of life with an integrated unified approach.
            </h2>
            {page.fields.intro ? (
              <p className="mt-5 text-base leading-relaxed text-muted-foreground">
                {page.fields.intro}
              </p>
            ) : null}
            <div className="mt-6">
              <RichText value={page.fields.body} />
            </div>
            <div className="mt-8 border-l-4 border-safety bg-white p-5">
              <p className="font-heading text-lg font-bold uppercase">
                {team[0]?.fields.name || "Ridgeform Leadership"}
              </p>
              <p className="mt-1 text-xs uppercase tracking-wider text-muted-foreground">
                {team[0]?.fields.role || "Principal / General Contractor"}
              </p>
            </div>
            <Link href="/contact" className="btn-cta btn-cta-dark mt-8">
              Get in touch
            </Link>
          </Reveal>
          {image?.url ? (
            <Reveal delay={100}>
              <div className="relative aspect-[4/5] overflow-hidden">
                <Image
                  src={image.url}
                  alt={assetAlt(image, "Ridgeform crew")}
                  fill
                  className="object-cover"
                  sizes="(max-width:768px) 100vw, 50vw"
                />
              </div>
            </Reveal>
          ) : null}
        </div>
      </section>

      <section className="bg-white py-20">
        <div className="site-shell">
          <Reveal>
            <h2 className="font-heading text-center text-3xl font-extrabold uppercase md:text-4xl">
              Our Specialization
            </h2>
          </Reveal>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {specialization.map((service, index) => (
              <Reveal key={service.uuid} delay={index * 70} className="h-full">
                <Link
                  href={`/services/${service.fields.slug}`}
                  className="group flex h-full flex-col border border-border p-6 hover:border-safety"
                >
                  <span className="font-heading text-5xl font-extrabold text-smoke group-hover:text-safety">
                    {index + 1}
                  </span>
                  <h3 className="font-heading mt-4 text-lg font-bold uppercase">
                    {service.fields.title}
                  </h3>
                  <p className="mt-3 flex-1 text-sm text-muted-foreground">
                    {service.fields.summary}
                  </p>
                  <span className="mt-4 inline-block text-xs font-bold uppercase tracking-wider">
                    Read More
                  </span>
                </Link>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {team.length > 0 ? (
        <section className="bg-smoke py-20">
          <div className="site-shell">
            <Reveal>
              <h2 className="font-heading text-center text-3xl font-extrabold uppercase">
                Our Team
              </h2>
              {page.fields["team-intro"] ? (
                <p className="mx-auto mt-4 max-w-2xl text-center text-muted-foreground">
                  {page.fields["team-intro"]}
                </p>
              ) : null}
            </Reveal>
            <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              {team.map((member, index) => {
                const photo = firstAsset(member.fields.photo);
                return (
                  <Reveal key={member.uuid} delay={index * 80}>
                    <div className="bg-white">
                      <div className="relative aspect-[4/5] overflow-hidden bg-muted">
                        {photo?.url ? (
                          <Image
                            src={photo.url}
                            alt={assetAlt(photo, member.fields.name || "Team")}
                            fill
                            className="object-cover"
                            sizes="(max-width:768px) 100vw, 33vw"
                          />
                        ) : null}
                      </div>
                      <div className="p-5 text-center">
                        <h3 className="font-heading text-lg font-bold uppercase">
                          {member.fields.name}
                        </h3>
                        <p className="mt-1 text-xs font-bold uppercase tracking-wider text-safety">
                          {member.fields.role}
                        </p>
                        {member.fields.bio ? (
                          <p className="mt-3 text-sm text-muted-foreground">
                            {member.fields.bio}
                          </p>
                        ) : null}
                      </div>
                    </div>
                  </Reveal>
                );
              })}
            </div>
          </div>
        </section>
      ) : null}

      {(page.fields["safety-title"] || page.fields["safety-body"]) && (
        <section className="py-20">
          <div className="site-shell max-w-3xl">
            <Reveal>
              <span className="section-label">About Summary</span>
              <h2 className="font-heading mt-4 text-3xl font-extrabold uppercase">
                {page.fields["safety-title"]}
              </h2>
              <div className="mt-6">
                <RichText value={page.fields["safety-body"]} />
              </div>
            </Reveal>
          </div>
        </section>
      )}
    </>
  );
}

// elmapicms-templates/nuxt-cove/app/pages/about.vue
<script setup lang="ts">
const { data } = await useFetch('/api/about', { key: 'about-page' })

const settings = computed(() => data.value?.settings)
const page = computed(() => data.value?.page)
const testimonials = computed(() => data.value?.testimonials || [])
const customers = computed(() => data.value?.customers || [])
const beliefs = computed(() =>
  asGroupList<{ title?: string, body?: string }>(page.value?.fields?.beliefs)
)

useCoveSeo({
  title: page.value?.fields?.['seo-title'] || page.value?.fields?.title,
  description: page.value?.fields?.['seo-description'] || page.value?.fields?.intro,
  path: '/about',
  siteName: settings.value?.fields?.['site-name'],
  siteUrl: settings.value?.fields?.['site-url'],
  defaultDescription: settings.value?.fields?.['seo-description'],
  defaultOgImage: firstAssetUrl(settings.value?.fields?.['og-image']),
  imageUrl: firstAssetUrl(page.value?.fields?.image)
})
</script>

<template>
  <article v-if="page">
    <PageHero
      eyebrow="About"
      :title="page.fields.title || 'About'"
      :intro="page.fields.intro"
      dark
    />

    <section class="border-b border-black/5 bg-white">
      <div class="cove-wrap grid items-center gap-10 py-14 lg:grid-cols-2">
        <CoveReveal>
          <img
            v-if="firstAssetUrl(page.fields.image)"
            :src="firstAssetUrl(page.fields.image)!"
            :alt="page.fields.title || 'About Cove'"
            class="aspect-[4/3] w-full rounded-2xl object-cover"
          >
        </CoveReveal>
        <CoveReveal :delay="100">
          <div>
            <span class="cove-pill">
              <span class="cove-pill-dot" />
              {{ page.fields['story-eyebrow'] || 'Our story' }}
            </span>
            <h2 class="mt-5 font-display text-3xl font-semibold tracking-tight text-ink-900">
              {{ page.fields['story-title'] || page.fields.title }}
            </h2>
            <p class="mt-4 text-lg leading-relaxed text-ink-500">
              {{ page.fields.intro }}
            </p>
          </div>
        </CoveReveal>
      </div>
    </section>

    <section class="cove-section">
      <div class="cove-wrap max-w-3xl">
        <CoveReveal>
          <RichText :html="data?.bodyHtml" />
        </CoveReveal>
      </div>
    </section>

    <section v-if="beliefs.length" class="cove-section bg-white">
      <div class="cove-wrap">
        <CoveReveal>
          <div class="mx-auto max-w-2xl text-center">
            <span class="cove-pill">
              <span class="cove-pill-dot" />
              What we believe
            </span>
            <h2 class="mt-5 font-display text-3xl font-semibold text-ink-900">
              {{ page.fields['beliefs-title'] || 'What we believe' }}
            </h2>
          </div>
        </CoveReveal>
        <div class="mt-12 grid gap-5 md:grid-cols-3">
          <CoveReveal
            v-for="(belief, index) in beliefs"
            :key="belief.title || String(index)"
            :delay="index * 80"
          >
            <div class="h-full rounded-2xl border border-black/5 bg-[var(--color-canvas)] p-6">
              <p class="font-display text-xl font-semibold text-ink-900">
                {{ belief.title }}
              </p>
              <p class="mt-3 text-sm leading-relaxed text-ink-500">
                {{ belief.body }}
              </p>
            </div>
          </CoveReveal>
        </div>
      </div>
    </section>

    <section class="cove-section">
      <div class="cove-wrap">
        <CoveReveal>
          <p class="text-center text-sm text-ink-400">
            {{ page.fields['customers-label'] || 'Teams shipping with Cove' }}
          </p>
        </CoveReveal>
        <div class="mt-6 flex flex-wrap items-center justify-center gap-x-10 gap-y-4">
          <span
            v-for="customer in customers"
            :key="customer.uuid"
            class="text-lg font-semibold tracking-wide text-ink-300"
          >
            {{ customer.fields.name }}
          </span>
        </div>

        <div class="mt-14 grid gap-5 lg:grid-cols-3">
          <CoveReveal
            v-for="(item, index) in testimonials"
            :key="item.uuid"
            :delay="index * 80"
          >
            <blockquote class="h-full rounded-2xl border border-black/5 bg-white p-6">
              <p class="text-base leading-relaxed text-ink-700">
                “{{ item.fields.quote }}”
              </p>
              <footer class="mt-5 text-sm text-ink-400">
                {{ item.fields['author-name'] }}
                <span v-if="item.fields.company"> · {{ item.fields.company }}</span>
              </footer>
            </blockquote>
          </CoveReveal>
        </div>
      </div>
    </section>

    <section class="bg-forest-700 text-white">
      <div class="cove-wrap py-16 text-center">
        <CoveReveal>
          <h2 class="font-display text-3xl font-semibold sm:text-4xl">
            {{ page.fields['cta-title'] }}
          </h2>
          <p class="mx-auto mt-4 max-w-xl text-white/75">
            {{ page.fields['cta-body'] }}
          </p>
          <div class="mt-8 flex flex-wrap justify-center gap-3">
            <UButton
              :to="page.fields['cta-primary-url'] || '/contact'"
              color="primary"
              size="lg"
            >
              <span class="text-forest-900">{{ page.fields['cta-primary-label'] || 'Contact us' }}</span>
            </UButton>
            <UButton
              :to="page.fields['cta-secondary-url'] || '/pricing'"
              color="neutral"
              variant="ghost"
              size="lg"
              class="text-white hover:bg-white/10"
            >
              {{ page.fields['cta-secondary-label'] || 'See pricing' }}
            </UButton>
          </div>
        </CoveReveal>
      </div>
    </section>
  </article>
</template>
