// elmapicms-templates/basic-starters/nextjs/components/locale-switcher.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { locales, localeLabels, type Locale } from "@/i18n/config";

type LocaleSwitcherProps = {
  locale: Locale;
  label: string;
};

/** Swap the leading /xx locale segment, keep the rest of the path. */
function pathForLocale(pathname: string, target: Locale): string {
  const segments = pathname.split("/");
  segments[1] = target;
  return segments.join("/") || `/${target}`;
}

export function LocaleSwitcher({ locale, label }: LocaleSwitcherProps) {
  const pathname = usePathname() || `/${locale}`;

  return (
    <div className="flex items-center gap-1" role="group" aria-label={label}>
      {locales.map((code) => (
        <Link
          key={code}
          href={pathForLocale(pathname, code)}
          className={
            code === locale
              ? "rounded px-2 py-1 text-xs font-medium uppercase bg-zinc-900 text-white"
              : "rounded px-2 py-1 text-xs font-medium uppercase text-zinc-600 hover:bg-zinc-100"
          }
          aria-current={code === locale ? "true" : undefined}
          title={localeLabels[code]}
        >
          {code}
        </Link>
      ))}
    </div>
  );
}

// elmapicms-templates/basic-starters/nuxt/app/components/LocaleSwitcher.vue
<script setup lang="ts">
import { locales, localeLabels, type Locale } from '~/utils/i18n'

defineProps<{
  locale: Locale
  label: string
}>()

const route = useRoute()

function pathForLocale(target: Locale) {
  const segments = route.path.split('/')
  segments[1] = target
  const path = segments.join('/') || `/${target}`
  const query = route.fullPath.includes('?')
    ? `?${route.fullPath.split('?')[1]}`
    : ''
  return `${path}${query}`
}
</script>

<template>
  <div class="flex items-center gap-1" role="group" :aria-label="label">
    <NuxtLink
      v-for="code in locales"
      :key="code"
      :to="pathForLocale(code)"
      class="rounded px-2 py-1 text-xs font-medium uppercase"
      :class="
        code === locale
          ? 'bg-zinc-900 text-white'
          : 'text-zinc-600 hover:bg-zinc-100'
      "
      :aria-current="code === locale ? 'true' : undefined"
      :title="localeLabels[code]"
    >
      {{ code }}
    </NuxtLink>
  </div>
</template>
