// elmapicms-templates/basic-starters/nuxt/app/pages/[locale]/notes/[slug].vue
<script setup lang="ts">
import { localePath } from '~/utils/i18n'

const { locale, dictionary } = useLocaleDict()
const route = useRoute()
const slug = computed(() => String(route.params.slug || ''))

const { data, error } = await useAsyncData(
  () => `note-${locale.value}-${slug.value}`,
  () =>
    $fetch(`/api/notes/${slug.value}`, {
      query: { locale: locale.value },
    }),
  { watch: [locale, slug] },
)

useHead({
  title: data.value?.note?.fields?.['seo-title'] || data.value?.note?.fields?.title,
  meta: [
    {
      name: 'description',
      content: data.value?.note?.fields?.['seo-description'] || '',
    },
  ],
  htmlAttrs: { lang: locale.value },
})
</script>

<template>
  <article class="space-y-6">
    <p
      v-if="error"
      class="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800"
    >
      {{ dictionary.errors.loadFailed }}
    </p>
    <template v-else-if="data?.note">
      <div>
        <NuxtLink
          :to="localePath(locale, '/notes')"
          class="text-sm text-zinc-500 underline underline-offset-2"
        >
          {{ dictionary.notes.backToList }}
        </NuxtLink>
        <h1 class="mt-3 text-2xl font-semibold tracking-tight">
          {{ data.note.fields.title }}
        </h1>
        <p
          v-if="data.note.fields['author-name']"
          class="mt-1 text-sm text-zinc-500"
        >
          {{ dictionary.notes.author }}: {{ data.note.fields['author-name'] }}
        </p>
      </div>
      <RichText :html="data.html" />
    </template>
  </article>
</template>

// elmapicms-templates/basic-starters/nextjs/app/[locale]/notes/[slug]/page.tsx
import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ElmapiError } from "@elmapicms/js-sdk";
import { RichText } from "@/components/rich-text";
import { getDictionary } from "@/i18n/dictionaries";
import { isLocale, localePath, type Locale } from "@/i18n/config";
import { getNoteBySlug } from "@/lib/content";

type PageProps = {
  params: Promise<{ locale: string; slug: string }>;
};

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { locale: raw, slug } = await params;
  if (!isLocale(raw)) return {};
  try {
    const note = await getNoteBySlug(raw, slug);
    if (!note) return { title: "Not found" };
    return {
      title: note.fields["seo-title"] || note.fields.title,
      description: note.fields["seo-description"],
    };
  } catch {
    return {};
  }
}

export default async function NotePage({ params }: PageProps) {
  const { locale: raw, slug } = await params;
  if (!isLocale(raw)) notFound();
  const locale: Locale = raw;
  const dictionary = getDictionary(locale);

  let note = null;
  try {
    note = await getNoteBySlug(locale, slug);
  } catch (error) {
    if (error instanceof ElmapiError) {
      return (
        <p className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">
          {dictionary.errors.loadFailed}
        </p>
      );
    }
    throw error;
  }

  if (!note) notFound();

  return (
    <article className="space-y-6">
      <div>
        <Link
          href={localePath(locale, "/notes")}
          className="text-sm text-zinc-500 underline underline-offset-2"
        >
          {dictionary.notes.backToList}
        </Link>
        <h1 className="mt-3 text-2xl font-semibold tracking-tight">
          {note.fields.title}
        </h1>
        {note.fields["author-name"] ? (
          <p className="mt-1 text-sm text-zinc-500">
            {dictionary.notes.author}: {note.fields["author-name"]}
          </p>
        ) : null}
      </div>
      <RichText value={note.fields.body} />
    </article>
  );
}
