// elmapicms-templates/nuxt-cove/app/pages/blog/[slug].vue
<script setup lang="ts">
const route = useRoute()
const { data, error } = await useFetch(`/api/blog/${route.params.slug}`, {
  key: `blog-${route.params.slug}`
})

if (error.value) {
  throw createError({
    statusCode: error.value.statusCode || 404,
    statusMessage: 'Post not found'
  })
}

const settings = computed(() => data.value?.settings)
const post = computed(() => data.value?.post)

useCoveSeo({
  title: post.value?.fields?.['seo-title'] || post.value?.fields?.title,
  description: post.value?.fields?.['seo-description'] || post.value?.fields?.excerpt,
  path: `/blog/${route.params.slug}`,
  siteName: settings.value?.fields?.['site-name'],
  siteUrl: settings.value?.fields?.['site-url'],
  defaultDescription: settings.value?.fields?.['seo-description'],
  defaultOgImage: firstAssetUrl(settings.value?.fields?.['og-image']),
  imageUrl:
    firstAssetUrl(post.value?.fields?.['og-image'])
    || firstAssetUrl(post.value?.fields?.['cover-image'])
})

function formatDate(value?: string | null) {
  if (!value) return ''
  return new Date(value).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}
</script>

<template>
  <article v-if="post">
    <PageHero
      eyebrow="Blog"
      :title="post.fields.title || 'Post'"
      :intro="post.fields.excerpt"
      dark
    />
    <div class="cove-wrap max-w-3xl py-14">
      <NuxtLink to="/blog" class="text-sm font-medium text-forest-700">
        ← All posts
      </NuxtLink>
      <p class="mt-4 text-sm text-ink-400">
        <span v-if="post.fields.author?.fields?.name">
          {{ post.fields.author.fields.name }}
        </span>
        <span v-if="post.published_at"> · {{ formatDate(post.published_at) }}</span>
      </p>
      <img
        v-if="firstAssetUrl(post.fields['cover-image'])"
        :src="firstAssetUrl(post.fields['cover-image'])!"
        :alt="post.fields.title || ''"
        class="mt-8 aspect-[16/9] w-full rounded-2xl object-cover"
      >
      <RichText class="mt-10" :html="data?.bodyHtml" />
    </div>
  </article>
</template>

// elmapicms-templates/nextjs-sable-goods/app/blog/[slug]/page.tsx
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { RichText } from "@/components/rich-text";
import { assetAlt, firstAsset } from "@/lib/assets";
import {
  getBlogPostBySlug,
  getBlogPostSlugs,
  getSiteSettings,
} from "@/lib/content";
import { formatDate } from "@/lib/format";
import { buildMetadata } from "@/lib/seo";
import {
  BLOG_TOPIC_LABELS,
  type BlogTopic,
} from "@/lib/types";

export const revalidate = 3600;

type PageProps = {
  params: Promise<{ slug: string }>;
};

export async function generateStaticParams() {
  try {
    const slugs = await getBlogPostSlugs();
    return slugs.map((slug) => ({ slug }));
  } catch {
    return [];
  }
}

export async function generateMetadata({ params }: PageProps) {
  const { slug } = await params;
  try {
    const [settings, post] = await Promise.all([
      getSiteSettings(),
      getBlogPostBySlug(slug),
    ]);
    const image = firstAsset(post.fields["cover-image"]);
    return buildMetadata({
      settings,
      title: post.fields["seo-title"] || post.fields.title,
      description: post.fields["seo-description"] || post.fields.excerpt,
      path: `/blog/${slug}`,
      imageUrl: image?.url,
    });
  } catch {
    return {};
  }
}

export default async function BlogPostPage({ params }: PageProps) {
  const { slug } = await params;

  let post;
  try {
    post = await getBlogPostBySlug(slug);
  } catch {
    notFound();
  }

  const image = firstAsset(post.fields["cover-image"]);
  const topic = post.fields.topic;
  const topicLabel =
    topic && topic in BLOG_TOPIC_LABELS
      ? BLOG_TOPIC_LABELS[topic as BlogTopic]
      : topic;
  const date = formatDate(post.published_at);

  return (
    <article>
      <header className="border-b border-border bg-mist">
        <div className="mx-auto max-w-3xl px-5 py-14 sm:px-8 lg:py-20">
          <p className="eyebrow">
            <Link href="/blog" className="hover:text-ink">
              Blog
            </Link>
            {topicLabel ? (
              <>
                <span className="mx-2 text-stone/50">/</span>
                <Link
                  href={`/blog?topic=${topic}`}
                  className="text-teal hover:text-ink"
                >
                  {topicLabel}
                </Link>
              </>
            ) : null}
          </p>
          <h1 className="section-title mt-4">{post.fields.title}</h1>
          {post.fields.excerpt ? (
            <p className="mt-5 text-lg leading-8 text-stone">
              {post.fields.excerpt}
            </p>
          ) : null}
          <div className="mt-6 flex flex-wrap gap-x-4 gap-y-1 text-[12px] font-medium uppercase tracking-[0.12em] text-stone">
            {post.fields["author-name"] ? (
              <span>{post.fields["author-name"]}</span>
            ) : null}
            {date ? <span>{date}</span> : null}
          </div>
        </div>
      </header>

      {image?.url ? (
        <div className="mx-auto max-w-5xl px-5 pt-10 sm:px-8">
          <div className="relative aspect-[16/9] overflow-hidden bg-mist">
            <Image
              src={image.url}
              alt={assetAlt(image, post.fields.title || "Blog post")}
              fill
              priority
              className="object-cover"
              sizes="(max-width: 1024px) 100vw, 960px"
            />
          </div>
        </div>
      ) : null}

      <div className="mx-auto max-w-3xl px-5 py-12 sm:px-8">
        <RichText value={post.fields.body} />
        <div className="mt-12 border-t border-border pt-8">
          <Link href="/blog" className="shop-cta-outline">
            Back to blog
          </Link>
        </div>
      </div>
    </article>
  );
}
