// elmapicms-templates/basic-starters/nextjs/app/[locale]/notes/page.tsx
import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ElmapiError } from "@elmapicms/js-sdk";
import { getDictionary } from "@/i18n/dictionaries";
import { isLocale, localePath, type Locale } from "@/i18n/config";
import {
  buildNotesWhere,
  countNotes,
  listNotes,
  listNotesOffset,
  type ListNotesOptions,
  type NoteSort,
} from "@/lib/content";

type PageProps = {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{
    page?: string;
    perPage?: string;
    title?: string;
    slug?: string;
    slugLike?: string;
    author?: string;
    after?: string;
    or?: string;
    sort?: string;
  }>;
};

export const metadata: Metadata = {
  title: "Notes",
};

const SORTS: NoteSort[] = [
  "published_at:desc",
  "published_at:asc",
  "title:asc",
  "title:desc",
];

function parseSort(value: string | undefined): NoteSort {
  if (value && (SORTS as string[]).includes(value)) {
    return value as NoteSort;
  }
  return "published_at:desc";
}

function buildQuery(params: Record<string, string | number | undefined>): string {
  const sp = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === "") continue;
    sp.set(key, String(value));
  }
  const qs = sp.toString();
  return qs ? `?${qs}` : "";
}

export default async function NotesPage({ params, searchParams }: PageProps) {
  const { locale: raw } = await params;
  if (!isLocale(raw)) notFound();
  const locale: Locale = raw;
  const dictionary = getDictionary(locale);
  const sp = await searchParams;

  const page = Math.max(1, Number(sp.page || "1") || 1);
  const perPage = [2, 5, 10].includes(Number(sp.perPage))
    ? Number(sp.perPage)
    : 5;
  const titleContains = (sp.title || "").trim();
  const slugEq = (sp.slug || "").trim();
  const slugContains = (sp.slugLike || "").trim();
  const authorContains = (sp.author || "").trim();
  const publishedAfter = (sp.after || "").trim();
  const matchTitleOrSlug = (sp.or || "").trim();
  const sort = parseSort(sp.sort);

  const listOptions: ListNotesOptions = {
    page,
    perPage,
    sort,
    titleContains: titleContains || undefined,
    slugEq: slugEq || undefined,
    slugContains: !slugEq && slugContains ? slugContains : undefined,
    authorContains: authorContains || undefined,
    publishedAfter: publishedAfter || undefined,
    matchTitleOrSlug: matchTitleOrSlug || undefined,
  };

  let notes: Awaited<ReturnType<typeof listNotes>> = { data: [], meta: {} };
  let totalCount = 0;
  let offsetSlice: Awaited<ReturnType<typeof listNotesOffset>> = [];
  let loadError: string | null = null;

  try {
    notes = await listNotes(locale, listOptions);
    totalCount = await countNotes(locale, listOptions);
    // Separate demo: first 2 matches via limit/offset (ignores page).
    offsetSlice = await listNotesOffset(locale, {
      ...listOptions,
      limit: 2,
      offset: 0,
    });
  } catch (error) {
    if (error instanceof ElmapiError) {
      loadError = dictionary.errors.loadFailed;
    } else {
      throw error;
    }
  }

  const lastPage = Math.max(1, notes.meta?.last_page ?? 1);
  const filterAction = localePath(locale, "/notes");
  const where = buildNotesWhere(listOptions);
  const queryPreview = {
    state: "published",
    locale,
    sort,
    paginate: perPage,
    page,
    ...(where ? { where } : {}),
  };

  const sharedParams = {
    title: titleContains || undefined,
    slug: slugEq || undefined,
    slugLike: slugContains || undefined,
    author: authorContains || undefined,
    after: publishedAfter || undefined,
    or: matchTitleOrSlug || undefined,
    sort,
    perPage,
  };

  const pageNumbers = Array.from({ length: lastPage }, (_, i) => i + 1).slice(
    0,
    8,
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">
          {dictionary.notes.title}
        </h1>
        <p className="mt-1 text-sm text-zinc-500">
          {totalCount} {dictionary.notes.results} · locale {locale}
        </p>
      </div>

      <form
        action={filterAction}
        method="get"
        className="space-y-3 rounded border border-zinc-200 bg-white p-4"
      >
        <h2 className="text-sm font-medium text-zinc-800">
          {dictionary.notes.filtersHeading}
        </h2>
        <div className="grid gap-3 sm:grid-cols-2">
          <label className="block space-y-1 text-sm">
            <span className="text-zinc-600">{dictionary.notes.titleContains}</span>
            <input
              name="title"
              defaultValue={titleContains}
              className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
              placeholder="BFF"
            />
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-zinc-600">{dictionary.notes.slugEq}</span>
            <input
              name="slug"
              defaultValue={slugEq}
              className="w-full rounded border border-zinc-300 px-3 py-2 font-mono text-sm"
              placeholder="hello-elmapi"
            />
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-zinc-600">{dictionary.notes.slugContains}</span>
            <input
              name="slugLike"
              defaultValue={slugContains}
              className="w-full rounded border border-zinc-300 px-3 py-2 font-mono text-sm"
              placeholder="filter"
            />
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-zinc-600">{dictionary.notes.authorContains}</span>
            <input
              name="author"
              defaultValue={authorContains}
              className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
            />
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-zinc-600">{dictionary.notes.publishedAfter}</span>
            <input
              name="after"
              type="date"
              defaultValue={publishedAfter}
              className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
            />
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-zinc-600">{dictionary.notes.orTerm}</span>
            <input
              name="or"
              defaultValue={matchTitleOrSlug}
              className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
              placeholder="hello"
            />
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-zinc-600">{dictionary.notes.sort}</span>
            <select
              name="sort"
              defaultValue={sort}
              className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
            >
              {SORTS.map((value) => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
            </select>
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-zinc-600">{dictionary.notes.perPage}</span>
            <select
              name="perPage"
              defaultValue={String(perPage)}
              className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
            >
              <option value="2">2</option>
              <option value="5">5</option>
              <option value="10">10</option>
            </select>
          </label>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            type="submit"
            className="rounded bg-zinc-900 px-3 py-2 text-sm text-white"
          >
            {dictionary.notes.applyFilter}
          </button>
          <Link
            href={filterAction}
            className="rounded border border-zinc-300 px-3 py-2 text-sm"
          >
            {dictionary.notes.clearFilter}
          </Link>
        </div>
        <p className="text-xs text-zinc-500">
          Tip: `or` uses `where.or` and overrides title/slug fields above. Exact
          `slug` uses `eq` and wins over `slugLike`.
        </p>
      </form>

      <details className="rounded border border-zinc-200 bg-zinc-50 p-3 text-sm">
        <summary className="cursor-pointer font-medium text-zinc-700">
          {dictionary.notes.queryPreview}
        </summary>
        <pre className="mt-2 overflow-x-auto font-mono text-xs text-zinc-700">
          {JSON.stringify(queryPreview, null, 2)}
        </pre>
      </details>

      {loadError ? (
        <p className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">
          {loadError}
        </p>
      ) : null}

      <ul className="divide-y divide-zinc-200 rounded border border-zinc-200 bg-white">
        {notes.data.length === 0 ? (
          <li className="px-4 py-3 text-sm text-zinc-500">{dictionary.notes.empty}</li>
        ) : (
          notes.data.map((note) => (
            <li key={note.uuid}>
              <Link
                href={localePath(locale, `/notes/${note.fields.slug}`)}
                className="block px-4 py-3 hover:bg-zinc-50"
              >
                <span className="font-medium">{note.fields.title}</span>
                <span className="mt-0.5 block font-mono text-xs text-zinc-500">
                  {note.fields.slug}
                  {note.fields["author-name"]
                    ? ` · ${note.fields["author-name"]}`
                    : ""}
                  {note.published_at
                    ? ` · ${note.published_at.slice(0, 10)}`
                    : ""}
                </span>
              </Link>
            </li>
          ))
        )}
      </ul>

      <div className="flex flex-wrap items-center justify-between gap-3 text-sm">
        <span className="text-zinc-500">
          {dictionary.notes.page} {page} / {lastPage}
          {notes.meta?.total != null ? ` · ${notes.meta.total} total` : ""}
        </span>
        <div className="flex flex-wrap gap-1">
          {page > 1 ? (
            <Link
              href={`${filterAction}${buildQuery({ ...sharedParams, page: page - 1 })}`}
              className="rounded border border-zinc-300 px-3 py-1.5"
            >
              {dictionary.notes.prev}
            </Link>
          ) : null}
          {pageNumbers.map((n) => (
            <Link
              key={n}
              href={`${filterAction}${buildQuery({ ...sharedParams, page: n })}`}
              className={
                n === page
                  ? "rounded bg-zinc-900 px-3 py-1.5 text-white"
                  : "rounded border border-zinc-300 px-3 py-1.5"
              }
            >
              {n}
            </Link>
          ))}
          {page < lastPage ? (
            <Link
              href={`${filterAction}${buildQuery({ ...sharedParams, page: page + 1 })}`}
              className="rounded border border-zinc-300 px-3 py-1.5"
            >
              {dictionary.notes.next}
            </Link>
          ) : null}
        </div>
      </div>

      <section className="space-y-2 rounded border border-dashed border-zinc-300 p-4">
        <h2 className="text-sm font-medium text-zinc-800">
          {dictionary.notes.offsetDemo}
        </h2>
        <p className="text-xs text-zinc-500">
          <code>listNotesOffset</code> uses <code>limit</code> +{" "}
          <code>offset</code> (returns a plain array, not page meta).
        </p>
        <ul className="text-sm text-zinc-700">
          {offsetSlice.length === 0 ? (
            <li className="text-zinc-500">{dictionary.notes.empty}</li>
          ) : (
            offsetSlice.map((note) => (
              <li key={note.uuid} className="font-mono text-xs">
                {note.fields.slug}
              </li>
            ))
          )}
        </ul>
      </section>
    </div>
  );
}

// elmapicms-templates/basic-starters/nuxt/app/pages/[locale]/notes/index.vue
<script setup lang="ts">
import { localePath } from '~/utils/i18n'

const { locale, dictionary } = useLocaleDict()
const route = useRoute()

const queryParams = computed(() => ({
  locale: locale.value,
  page: Number(route.query.page || 1) || 1,
  perPage: Number(route.query.perPage || 5) || 5,
  title: String(route.query.title || ''),
  slug: String(route.query.slug || ''),
  slugLike: String(route.query.slugLike || ''),
  author: String(route.query.author || ''),
  after: String(route.query.after || ''),
  or: String(route.query.or || ''),
  sort: String(route.query.sort || 'published_at:desc'),
}))

const { data, error, refresh } = await useAsyncData(
  () => `notes-${locale.value}-${JSON.stringify(queryParams.value)}`,
  () => $fetch('/api/notes', { query: queryParams.value }),
  { watch: [queryParams] },
)

useHead({
  title: dictionary.value.notes.title,
  htmlAttrs: { lang: locale.value },
})

const lastPage = computed(() => Math.max(1, data.value?.notes?.meta?.last_page ?? 1))
const page = computed(() => queryParams.value.page)
const pageNumbers = computed(() =>
  Array.from({ length: lastPage.value }, (_, i) => i + 1).slice(0, 8),
)

function hrefFor(overrides: Record<string, string | number | undefined>) {
  const next = { ...queryParams.value, ...overrides }
  const sp = new URLSearchParams()
  for (const [key, value] of Object.entries(next)) {
    if (key === 'locale') continue
    if (value === undefined || value === '' || value === null) continue
    sp.set(key, String(value))
  }
  const qs = sp.toString()
  return `${localePath(locale.value, '/notes')}${qs ? `?${qs}` : ''}`
}

async function onFilter(event: Event) {
  event.preventDefault()
  const form = event.target as HTMLFormElement
  const fd = new FormData(form)
  const query: Record<string, string> = {}
  for (const [key, value] of fd.entries()) {
    const v = String(value).trim()
    if (v) query[key] = v
  }
  await navigateTo({ path: localePath(locale.value, '/notes'), query })
  await refresh()
}
</script>

<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-2xl font-semibold tracking-tight">
        {{ dictionary.notes.title }}
      </h1>
      <p class="mt-1 text-sm text-zinc-500">
        {{ data?.total ?? 0 }} {{ dictionary.notes.results }} · locale {{ locale }}
      </p>
    </div>

    <form
      class="space-y-3 rounded border border-zinc-200 bg-white p-4"
      @submit="onFilter"
    >
      <h2 class="text-sm font-medium text-zinc-800">
        {{ dictionary.notes.filtersHeading }}
      </h2>
      <div class="grid gap-3 sm:grid-cols-2">
        <label class="block space-y-1 text-sm">
          <span class="text-zinc-600">{{ dictionary.notes.titleContains }}</span>
          <input
            name="title"
            :value="queryParams.title"
            class="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
          >
        </label>
        <label class="block space-y-1 text-sm">
          <span class="text-zinc-600">{{ dictionary.notes.slugEq }}</span>
          <input
            name="slug"
            :value="queryParams.slug"
            class="w-full rounded border border-zinc-300 px-3 py-2 font-mono text-sm"
          >
        </label>
        <label class="block space-y-1 text-sm">
          <span class="text-zinc-600">{{ dictionary.notes.slugContains }}</span>
          <input
            name="slugLike"
            :value="queryParams.slugLike"
            class="w-full rounded border border-zinc-300 px-3 py-2 font-mono text-sm"
          >
        </label>
        <label class="block space-y-1 text-sm">
          <span class="text-zinc-600">{{ dictionary.notes.authorContains }}</span>
          <input
            name="author"
            :value="queryParams.author"
            class="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
          >
        </label>
        <label class="block space-y-1 text-sm">
          <span class="text-zinc-600">{{ dictionary.notes.publishedAfter }}</span>
          <input
            name="after"
            type="date"
            :value="queryParams.after"
            class="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
          >
        </label>
        <label class="block space-y-1 text-sm">
          <span class="text-zinc-600">{{ dictionary.notes.orTerm }}</span>
          <input
            name="or"
            :value="queryParams.or"
            class="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
          >
        </label>
        <label class="block space-y-1 text-sm">
          <span class="text-zinc-600">{{ dictionary.notes.sort }}</span>
          <select
            name="sort"
            :value="queryParams.sort"
            class="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
          >
            <option value="published_at:desc">published_at:desc</option>
            <option value="published_at:asc">published_at:asc</option>
            <option value="title:asc">title:asc</option>
            <option value="title:desc">title:desc</option>
          </select>
        </label>
        <label class="block space-y-1 text-sm">
          <span class="text-zinc-600">{{ dictionary.notes.perPage }}</span>
          <select
            name="perPage"
            :value="String(queryParams.perPage)"
            class="w-full rounded border border-zinc-300 px-3 py-2 text-sm"
          >
            <option value="2">2</option>
            <option value="5">5</option>
            <option value="10">10</option>
          </select>
        </label>
      </div>
      <div class="flex flex-wrap gap-2">
        <button type="submit" class="rounded bg-zinc-900 px-3 py-2 text-sm text-white">
          {{ dictionary.notes.applyFilter }}
        </button>
        <NuxtLink
          :to="localePath(locale, '/notes')"
          class="rounded border border-zinc-300 px-3 py-2 text-sm"
        >
          {{ dictionary.notes.clearFilter }}
        </NuxtLink>
      </div>
    </form>

    <details class="rounded border border-zinc-200 bg-zinc-50 p-3 text-sm">
      <summary class="cursor-pointer font-medium text-zinc-700">
        {{ dictionary.notes.queryPreview }}
      </summary>
      <pre class="mt-2 overflow-x-auto font-mono text-xs text-zinc-700">{{ JSON.stringify(data?.query || {}, null, 2) }}</pre>
    </details>

    <p
      v-if="error"
      class="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800"
    >
      {{ dictionary.errors.loadFailed }}
    </p>

    <ul class="divide-y divide-zinc-200 rounded border border-zinc-200 bg-white">
      <li
        v-if="!data?.notes?.data?.length"
        class="px-4 py-3 text-sm text-zinc-500"
      >
        {{ dictionary.notes.empty }}
      </li>
      <li v-for="note in data?.notes?.data || []" :key="note.uuid">
        <NuxtLink
          :to="localePath(locale, `/notes/${note.fields.slug}`)"
          class="block px-4 py-3 hover:bg-zinc-50"
        >
          <span class="font-medium">{{ note.fields.title }}</span>
          <span class="mt-0.5 block font-mono text-xs text-zinc-500">
            {{ note.fields.slug }}
            <template v-if="note.fields['author-name']">
              · {{ note.fields['author-name'] }}
            </template>
            <template v-if="note.published_at">
              · {{ note.published_at.slice(0, 10) }}
            </template>
          </span>
        </NuxtLink>
      </li>
    </ul>

    <div class="flex flex-wrap items-center justify-between gap-3 text-sm">
      <span class="text-zinc-500">
        {{ dictionary.notes.page }} {{ page }} / {{ lastPage }}
      </span>
      <div class="flex flex-wrap gap-1">
        <NuxtLink
          v-if="page > 1"
          :to="hrefFor({ page: page - 1 })"
          class="rounded border border-zinc-300 px-3 py-1.5"
        >
          {{ dictionary.notes.prev }}
        </NuxtLink>
        <NuxtLink
          v-for="n in pageNumbers"
          :key="n"
          :to="hrefFor({ page: n })"
          class="rounded px-3 py-1.5"
          :class="n === page ? 'bg-zinc-900 text-white' : 'border border-zinc-300'"
        >
          {{ n }}
        </NuxtLink>
        <NuxtLink
          v-if="page < lastPage"
          :to="hrefFor({ page: page + 1 })"
          class="rounded border border-zinc-300 px-3 py-1.5"
        >
          {{ dictionary.notes.next }}
        </NuxtLink>
      </div>
    </div>

    <section class="space-y-2 rounded border border-dashed border-zinc-300 p-4">
      <h2 class="text-sm font-medium text-zinc-800">
        {{ dictionary.notes.offsetDemo }}
      </h2>
      <ul class="text-sm text-zinc-700">
        <li
          v-if="!data?.offsetSlice?.length"
          class="text-zinc-500"
        >
          {{ dictionary.notes.empty }}
        </li>
        <li
          v-for="note in data?.offsetSlice || []"
          :key="note.uuid"
          class="font-mono text-xs"
        >
          {{ note.fields.slug }}
        </li>
      </ul>
    </section>
  </div>
</template>
